-------------------PROBAR OBJETO--------------------------
SET SERVEROUTPUT ON FORMAT WRAPPED LINE 1000;

DECLARE 
V1 PRODUCTO;
BEGIN
V1:=PRODUCTO(100,'Manzana',10);
DBMS_OUTPUT.PUT_LINE(V1.VER_PRECIO());
V1.MAYUS();
DBMS_OUTPUT.PUT_LINE(V1.VER_PRODUCTO);
END;
/
-----------------------------METODOS ESTATICOS-----------------------------
SET SERVEROUTPUT ON FORMAT WRAPPED LINE 1000;

DECLARE 
V1 PRODUCTO;
BEGIN
V1:=PRODUCTO(100,'Manzana',10);
DBMS_OUTPUT.PUT_LINE(V1.VER_PRECIO());
V1.MAYUS();
DBMS_OUTPUT.PUT_LINE(V1.VER_PRODUCTO);
PRODUCTO.AUDITORIA();
END;
/
SELECT * FROM AUDITORIA;