------------------INTRODUCCION  A LOS OBJETOS-----------------------------------
/*ORACLE ES UNA BASE DE DATOS DE TIPO RELACIONAL Y POR LO TANTO NO ES UNA BASE 
DE DATOS DE TIPOS OBJETO
SIN EMBARGO INCORPORO FUNCIONALIDADES QUE PERMITEN TRABAJAR CON ALGUNAS DE LAS
CARACTERISTICAS DE LAS BASES DE DATOS ORINTADAS A OBJETO
*/

----------------------CREAR TIPOS DE OBJETOS-----------------------------------
CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PVP NUMBER),
MEMBER PROCEDURE MAYUS
);
/

DROP TYPE PRODUCTO;

-----------------------CREAR UN TIPO DE OBJETO CUERPO--------------------------
CREATE OR REPLACE TYPE BODY PRODUCTO AS 

MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2 AS
BEGIN
RETURN 'CODIGO => '||CODIGO||' NOMBRE =>'||NOMBRE||' PRECIO =>'||PRECIO;
END VER_PRODUCTO;

MEMBER FUNCTION VER_PRECIO RETURN NUMBER AS
BEGIN
RETURN PRECIO;
END VER_PRECIO;

MEMBER PROCEDURE CAMBIAR_PRECIO(PVP NUMBER)AS
BEGIN
PRECIO:=PRECIO;
END CAMBIAR_PRECIO;

MEMBER PROCEDURE MAYUS AS 
BEGIN
NOMBRE:=UPPER(NOMBRE);
END MAYUS;

END;
/

--------------------------------ARGUMENTO SELF---------------------------------

CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER),
MEMBER PROCEDURE MAYUS
);
/
------------------
CREATE OR REPLACE TYPE BODY PRODUCTO AS 

MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2 AS
BEGIN
RETURN 'CODIGO => '||CODIGO||' NOMBRE =>'||NOMBRE||' PRECIO =>'||PRECIO;
END VER_PRODUCTO;

MEMBER FUNCTION VER_PRECIO RETURN NUMBER AS
BEGIN
RETURN PRECIO;
END VER_PRECIO;

MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER)AS
BEGIN
SELF.PRECIO:=PRECIO;
END CAMBIAR_PRECIO;

MEMBER PROCEDURE MAYUS AS 
BEGIN
NOMBRE:=UPPER(NOMBRE);
END MAYUS;

END;
/

-----------------------------METODOS ESTATICOS-----------------------------

CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER),
MEMBER PROCEDURE MAYUS,
STATIC PROCEDURE AUDITORIA
);

CREATE OR REPLACE TYPE BODY PRODUCTO AS 

MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2 AS
BEGIN
RETURN 'CODIGO => '||CODIGO||' NOMBRE =>'||NOMBRE||' PRECIO =>'||PRECIO;
END VER_PRODUCTO;

MEMBER FUNCTION VER_PRECIO RETURN NUMBER AS
BEGIN
RETURN PRECIO;
END VER_PRECIO;

MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER)AS
BEGIN
SELF.PRECIO:=PRECIO;
END CAMBIAR_PRECIO;

MEMBER PROCEDURE MAYUS AS 
BEGIN
NOMBRE:=UPPER(NOMBRE);
END MAYUS;

STATIC PROCEDURE AUDITORIA
AS BEGIN
INSERT INTO AUDITORIA VALUES(USER,SYSDATE);
END AUDITORIA;
END;
/

----------------------------METODOS CONSTRUCTORES--------------------------

CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER),
MEMBER PROCEDURE MAYUS,
STATIC PROCEDURE AUDITORIA,
CONSTRUCTOR FUNCTION PRODUCTO (N1 VARCHAR2) RETURN SELF AS RESULT
);


CREATE OR REPLACE TYPE BODY PRODUCTO AS 

MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2 AS
BEGIN
RETURN 'CODIGO => '||CODIGO||' NOMBRE =>'||NOMBRE||' PRECIO =>'||PRECIO;
END VER_PRODUCTO;

MEMBER FUNCTION VER_PRECIO RETURN NUMBER AS
BEGIN
RETURN PRECIO;
END VER_PRECIO;

MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER)AS
BEGIN
SELF.PRECIO:=PRECIO;
END CAMBIAR_PRECIO;

MEMBER PROCEDURE MAYUS AS 
BEGIN
NOMBRE:=UPPER(NOMBRE);
END MAYUS;

STATIC PROCEDURE AUDITORIA
AS BEGIN
INSERT INTO AUDITORIA VALUES(USER,SYSDATE);
END AUDITORIA;

CONSTRUCTOR FUNCTION PRODUCTO (N1 VARCHAR2) RETURN SELF AS RESULT
IS
BEGIN
SELF.NOMBRE:=N1;
SELF.PRECIO:=NULL;
SELF.CODIGO:=SEQ1.NEXTVAL;
RETURN;
END PRODUCTO;
END;
/

----------------------------Comprobar los objetos que tenemos-------------------

desc PRODUCTO;

DESC EMPLEADO;

SELECT * FROM USER_TYPES;

SELECT * FROM USER_SOURCE WHERE NAME='PRODUCTO';

------------------------SOBRECARGA DE OPERADORES--------------------------------

CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER FUNCTION VER_PRECIO(IMPUESTO NUMBER) RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER),
MEMBER PROCEDURE MAYUS,
STATIC PROCEDURE AUDITORIA
);

---------------
CREATE OR REPLACE TYPE BODY PRODUCTO AS 

MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2 AS
BEGIN
RETURN 'CODIGO => '||CODIGO||' NOMBRE =>'||NOMBRE||' PRECIO =>'||PRECIO;
END VER_PRODUCTO;

MEMBER FUNCTION VER_PRECIO RETURN NUMBER AS
BEGIN
RETURN PRECIO;
END VER_PRECIO;

MEMBER FUNCTION VER_PRECIO(IMPUESTO NUMBER) RETURN NUMBER AS
BEGIN
RETURN PRECIO - PRECIO*IMPUESTO/100;
END;

MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER)AS
BEGIN
SELF.PRECIO:=PRECIO;
END CAMBIAR_PRECIO;

MEMBER PROCEDURE MAYUS AS 
BEGIN
NOMBRE:=UPPER(NOMBRE);
END MAYUS;

STATIC PROCEDURE AUDITORIA
AS BEGIN
INSERT INTO AUDITORIA VALUES(USER,SYSDATE);
END AUDITORIA;

END;
/

--------------------------------------HERENCIA------------------------------
CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER FUNCTION VER_PRECIO(IMPUESTO NUMBER) RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PRECIO NUMBER),
MEMBER PROCEDURE MAYUS,
STATIC PROCEDURE AUDITORIA
)
NOT FINAL
;



-----
CREATE OR REPLACE TYPE COMESTIBLE UNDER PRODUCTO(
CADUCIDAD DATE,
MEMBER FUNCTION VER_CADUCIDAD RETURN VARCHAR2
);
/

CREATE OR REPLACE TYPE BODY COMESTIBLE AS 
MEMBER FUNCTION VER_CADUCIDAD RETURN VARCHAR2 AS
BEGIN
RETURN CADUCIDAD;
END;
END;
/

---------------------------------SOBRE ESCRIBIR METODOS----------------------
CREATE OR REPLACE TYPE COMESTIBLE UNDER PRODUCTO(
CADUCIDAD DATE,
MEMBER FUNCTION VER_CADUCIDAD RETURN VARCHAR2,
OVERRIDING MEMBER FUNCTION VER_PRECIO RETURN NUMBER
);

CREATE OR REPLACE TYPE BODY COMESTIBLE AS 
MEMBER FUNCTION VER_CADUCIDAD RETURN VARCHAR2 AS
BEGIN
RETURN CADUCIDAD;
END;

OVERRIDING MEMBER FUNCTION VER_PRECIO RETURN NUMBER
AS BEGIN
RETURN PRECIO + 10;
END;

END;
/

-----------------CREAR UNA COLUMNA DE TIPO OBJETO EN UNA TABLA------------------

CREATE TABLE TIENDA(
CODIGO NUMBER,
ESTANTERIA NUMBER,
PRODUCTO PRODUCTO
);

DESC TIENDA;

INSERT INTO TIENDA VALUES(1,1,PRODUCTO(1,'LIMON',90));


SELECT * FROM TIENDA;

SELECT T.PRODUCTO.PRECIO FROM TIENDA T;

SELECT T.PRODUCTO.VER_PRODUCTO() FROM TIENDA T;
 -- NO SE PUEDE UTILIZAR LOS METODO QUE TENGAN QUE INSERTAR O ALCTUALIZA 
































































