---------------------PROCEDIMIENTOS Y FUNCIONES--------------------------------

/*
1- CREACION EL ONJETO
   CODIGO FUENTE
   CODIGO PSEUDO-COMPILADO

2- INVOCAR EN CUALQUIER MOMENTO (SQL)

NOS PERMITE CREAR PROGRAMAS PL/SQL QUE GUARDAMOS DENTRO DE LA BASE DE DATOS Y
QUE LUEGO PODEMOS REUTILIZAR
*/

-----------------------------CREAR UN PROCEDIMIENTO----------------------------
--LOS BLOQUES ANONIMOS CUNADO LOS LANZO SE EJECUTAN PERO LOS PROCEDIMIENTOS NO
--CUANDO CREO UN PROCEDIMIENTO SE GUARDA EN LA BASE DE DATOS.
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE PR1
IS
X NUMBER:=10;
BEGIN
DBMS_OUTPUT.PUT_LINE(X);
END;
/
----------------VER CODIGO FUENTES DE PROCEDIMIENTOS Y FUNCIONES----------------
--USER_OBJECTS

SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE='PROCEDURE';

SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS GROUP BY OBJECT_TYPE;

SELECT * FROM USER_SOURCE WHERE NAME='PR1';