------------------INTRODUCCION  A LOS OBJETOS-----------------------------------
/*ORACLE ES UNA BASE DE DATOS DE TIPO RELACIONAL Y POR LO TANTO NO ES UNA BASE 
DE DATOS DE TIPOS OBJETO
SIN EMBARGO INCORPORO FUNCIONALIDADES QUE PERMITEN TRABAJAR CON ALGUNAS DE LAS
CARACTERISTICAS DE LAS BASES DE DATOS ORINTADAS A OBJETO
*/

----------------------CREAR TIPOS DE OBJETOS-----------------------------------
CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(

--ATRIBUTO
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO NUMBER,

--METODOS
MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
MEMBER PROCEDURE CAMBIAR_PRECIO(PVP NUMBER)
);
/

DROP TYPE PRODUCTO;