---------------------PROCEDIMIENTOS Y FUNCIONES--------------------------------

/*
1- CREACION EL ONJETO
   CODIGO FUENTE
   CODIGO PSEUDO-COMPILADO

2- INVOCAR EN CUALQUIER MOMENTO (SQL)

NOS PERMITE CREAR PROGRAMAS PL/SQL QUE GUARDAMOS DENTRO DE LA BASE DE DATOS Y
QUE LUEGO PODEMOS REUTILIZAR
*/